version: '2.1'
services:
  app:
    extends:
      file: docker-compose.base.yml
      service: app
    ports:
    - "${APP_PORT}:80"
  mysql:
    extends:
      file: docker-compose.base.yml
      service: mysql
    ports:
    - "${DB_PORT}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASS}"
      MYSQL_DATABASE: "${DB_NAME}"
      MYSQL_USER: "${DB_USER}"
      MYSQL_PASSWORD: "${DB_PASS}"
networks:
  wpnet:
    driver: "bridge"
volumes:
  mysqldata:
    driver: "local"
